# Generated by Django 3.1.13 on 2021-09-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('webapp_0', '0003_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_homeerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='index',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='index',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Base_HomeeRelatedLink',
        ),
        migrations.DeleteModel(
            name='index',
        ),
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
