# Generated by Django 3.1.13 on 2021-09-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0005_consultas_galeriadeimagenes_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='Adv_url',
            field=models.URLField(blank=True, null=True, verbose_name='Advertising-url'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date1',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-1'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date10',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-10'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date11',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-11'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date12',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-12'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date13',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-13'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date14',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-14'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date15',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-15'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date16',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-16'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date17',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-17'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date18',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-18'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date19',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-19'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-2'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date20',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-20'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date3',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-3'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date4',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-4'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date5',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-5'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date6',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-6'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date7',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-7'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date8',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-8'),
        ),
        migrations.AlterField(
            model_name='index',
            name='TS_date9',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tearsheet-9'),
        ),
    ]
