# Generated by Django 3.1.13 on 2021-09-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0007_indexpagerelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='Adv_url',
        ),
    ]
