# Generated by Django 3.1.13 on 2021-09-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('webapp_0', '0008_remove_index_adv_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_17',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_18',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_19',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_20',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_21',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_22',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_23',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_24',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='index',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indexpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='consultas',
        ),
        migrations.DeleteModel(
            name='GaleriadeImagenes',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='IndexPageRelatedLink',
        ),
    ]
