# Generated by Django 3.1.13 on 2021-09-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_0', '0013_documentary_galeriadeimagenes4_galeriadeimagenes5_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes2',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes3',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes4',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes5',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo'),
        ),
    ]
