# Generated by Django 3.1.13 on 2021-10-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_0', '0014_auto_20210930_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil'),
        ),
    ]
