# Generated by Django 3.1.13 on 2021-10-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('webapp_0', '0016_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
