# Generated by Django 3.1.13 on 2021-10-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0019_socialmediasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='page',
        ),
        migrations.DeleteModel(
            name='IndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
