# Generated by Django 3.1.13 on 2021-10-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0023_newsdetailpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='news_image',
        ),
    ]
