# Generated by Django 3.1.13 on 2021-10-12 21:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0024_auto_20211011_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='banner_title4',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-1 '),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title5',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-2  '),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title6',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-3  '),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title7',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
    ]
