# Generated by Django 3.1.13 on 2021-10-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0025_auto_20211012_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetailpage',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='author',
            field=models.CharField(blank=True, help_text='Nombre del Autor ', max_length=100, null=True),
        ),
    ]
