# Generated by Django 3.1.13 on 2021-10-13 22:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0028_auto_20211013_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_prod',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields_Prod_2', to='webapp_0.productos'),
        ),
    ]
