# Generated by Django 3.1.13 on 2021-10-15 17:21

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0033_auto_20211013_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='Ad_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Advertising info'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='Ad_link',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Enlace para volver al inicio'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='Ad_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Documentary info'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='Ad_link',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Enlace para volver al inicio'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='Ad_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Advertising info'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='Ad_link',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Enlace para volver al inicio'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Ad_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Advertising info'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Ad_link',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Enlace para volver al inicio'),
        ),
    ]
