# Generated by Django 3.1.13 on 2021-10-16 00:54

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0034_auto_20211015_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_doc',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp_0.documentary'),
        ),
    ]
