# Generated by Django 3.1.14 on 2022-03-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_0', '0038_galeriadeimagenes_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='banner_info1',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_info2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_info3',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title1',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title3',
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_10_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_4_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_5_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_6_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_7_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_8_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_9_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
    ]
