# Generated by Django 3.1.14 on 2022-03-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0039_auto_20220302_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='web_title',
        ),
        migrations.AddField(
            model_name='index',
            name='cliente_Navbar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tearsheet-1 info'),
        ),
    ]
