# Generated by Django 3.1.14 on 2022-03-06 03:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0043_galeriadeimagenes2_publicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='rseña bibliografica'),
        ),
    ]
