# Generated by Django 3.1.14 on 2022-03-06 06:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_0', '0044_index_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes2',
            name='consulta',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos consulten por el formulario'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes2',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='consulta',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos consulten por el formulario'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp_0.publicidad'),
        ),
    ]
